/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pages;

/**
 *
 * @author godpo
 */
public class AboutProgram extends javax.swing.JFrame {

    /**
     * Creates new form AboutProgram
     */
    public AboutProgram() {
        initComponents();
        DisplayAbout.setText("<html> This program was originally pionnered and <br> conceived through the ingenuity of Major <br> General Richard W. "
                             + "Zhang of Northwest Enclave <br> Scientific Development Division in B.C. 2150. <br> After more than a decade of continuous develo <br> pment, the grand idea of near instant long <br>" 
                             + "distance logistics communication was realized <br> after a herculean efforts of re-starting ancient <br>"
                             + "communication satelites in orbit and establish <br> communications with ground based control <br>"
                             + "centers and orbital control sub-stations. <br> <br> Lieutenant Colonel, Michael Campbell, Northwes <br>"
                             + "t Enclave Archives Division, October 3rd, 2178. </html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        DisplayAbout = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AboutBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("ABOUT THIS PROGRAM:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 350, 40));

        DisplayAbout.setBackground(new java.awt.Color(0, 0, 0));
        DisplayAbout.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        DisplayAbout.setForeground(new java.awt.Color(255, 0, 51));
        DisplayAbout.setText("jLabel2");
        getContentPane().add(DisplayAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 470, 400));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, -1));

        AboutBackground.setIcon(new javax.swing.ImageIcon("P:\\Coding Files\\EnclaveSystem\\InformationAccess\\src\\main\\java\\VisualFiles\\AboutBackground2.jpg")); // NOI18N
        getContentPane().add(AboutBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutBackground;
    private javax.swing.JLabel DisplayAbout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
