/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pages;

/**
 *
 * @author godpo
 */
public class AccessDenied extends javax.swing.JFrame {

    /**
     * Creates new form AccessDenied
     */
    public AccessDenied() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AcknowledgedButton = new javax.swing.JButton();
        AccessDeniedBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AcknowledgedButton.setBackground(new java.awt.Color(0, 0, 0));
        AcknowledgedButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AcknowledgedButton.setForeground(new java.awt.Color(0, 255, 0));
        AcknowledgedButton.setText("ACKNOWLEDGED");
        AcknowledgedButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AcknowledgedButton.setMaximumSize(new java.awt.Dimension(100, 30));
        AcknowledgedButton.setMinimumSize(new java.awt.Dimension(100, 30));
        AcknowledgedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcknowledgedButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AcknowledgedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 225, 160, -1));

        AccessDeniedBackground.setIcon(new javax.swing.ImageIcon("P:\\Coding Files\\EnclaveSystem\\InformationAccess\\src\\main\\java\\VisualFiles\\AccessDenied.jpg")); // NOI18N
        jPanel1.add(AccessDeniedBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcknowledgedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcknowledgedButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_AcknowledgedButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccessDenied.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccessDenied.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccessDenied.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccessDenied.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccessDenied().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccessDeniedBackground;
    private javax.swing.JButton AcknowledgedButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
