package Pages;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author godpo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UsernameInput = new javax.swing.JTextField();
        PasswordInput = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        RegistrateButton = new javax.swing.JButton();
        LoginBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("Enclave Library System Login: Welcome Commander! ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, -1, 37));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 51));
        jLabel2.setText("Username:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 51));
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, -1, -1));

        UsernameInput.setBackground(new java.awt.Color(0, 0, 0));
        UsernameInput.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        UsernameInput.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(UsernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 260, 400, -1));

        PasswordInput.setBackground(new java.awt.Color(0, 0, 0));
        PasswordInput.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        PasswordInput.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PasswordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 390, 399, -1));

        LoginButton.setBackground(new java.awt.Color(0, 0, 204));
        LoginButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 520, -1, -1));

        CancelButton.setBackground(new java.awt.Color(153, 0, 0));
        CancelButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(255, 255, 255));
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 520, -1, -1));

        RegistrateButton.setBackground(new java.awt.Color(0, 153, 51));
        RegistrateButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        RegistrateButton.setForeground(new java.awt.Color(255, 255, 255));
        RegistrateButton.setText("Registrate");
        RegistrateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 520, 160, -1));

        LoginBackground.setIcon(new javax.swing.ImageIcon("P:\\Coding Files\\EnclaveSystem\\InformationAccess\\src\\main\\java\\VisualFiles\\TrueBackGround#1.jpg")); // NOI18N
        getContentPane().add(LoginBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1770, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrateButtonActionPerformed
        Registration rgf = new Registration();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_RegistrateButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        String username = UsernameInput.getText().trim();
        String password = String.valueOf(PasswordInput.getPassword());
        
        ResultSet validateResult;
        PreparedStatement ps;
        
        String query = "SELECT * FROM registeredusers WHERE userName = ? AND passWord = ?";
        
        try {
            ps = DataLink.getConnection().prepareStatement(query);
            ps.setString(1, username);
            ps.setString(2, password);
            
            validateResult = ps.executeQuery();
            
            if(validateResult.next()){
                query = "INSERT INTO currentuser SELECT * FROM registeredusers WHERE userName = ? AND passWord = ?";
                ps = DataLink.getConnection().prepareStatement(query);
                ps.setString(1, username);
                ps.setString(2, password);
                ps.executeUpdate();
                Dashboard centralConsole = new Dashboard();
                centralConsole.setVisible(true);
                centralConsole.setLocationRelativeTo(null);
                this.dispose();
            } else {
                AccessDenied ad = new AccessDenied();
                ad.setVisible(true);
                ad.pack();
                ad.setLocationRelativeTo(LoginButton);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        UsernameInput.setText(null);
        PasswordInput.setText(null);
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel LoginBackground;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PasswordInput;
    private javax.swing.JButton RegistrateButton;
    private javax.swing.JTextField UsernameInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
