package Pages;


import Pages.Login;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author godpo
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    
    //Fields
    
    final ImageIcon icon;
    public Registration() {
        initComponents();
        icon = new ImageIcon("P:\\Coding Files\\EnclaveSystem\\InformationAccess\\src\\main\\java\\VisualFiles\\correctIconSmol.png");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e){
                closingSequence();
            }
    });

        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegisTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LastNameInput = new javax.swing.JTextField();
        FirstNameInput = new javax.swing.JTextField();
        UsernameInput = new javax.swing.JTextField();
        RankInput = new javax.swing.JTextField();
        PasswordInput = new javax.swing.JPasswordField();
        PasswordConfirmation = new javax.swing.JPasswordField();
        BirthdateInput = new javax.swing.JFormattedTextField();
        confirmRegistration = new javax.swing.JButton();
        clearRegistration = new javax.swing.JButton();
        backToLogin = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegisTitle.setBackground(new java.awt.Color(0, 0, 0));
        RegisTitle.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        RegisTitle.setForeground(new java.awt.Color(255, 255, 255));
        RegisTitle.setText("Enclave Library System Registration");
        jPanel1.add(RegisTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 730, 100));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("First Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 146, -1, 32));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Username:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 234, -1, 32));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 51));
        jLabel3.setText("Last Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 190, -1, 32));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("Rank:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 316, -1, 32));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 51));
        jLabel5.setText("Password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 360, -1, 32));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 51));
        jLabel6.setText("Birthdate:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 273, -1, 32));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 51));
        jLabel7.setText("Confirm Password:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 404, -1, 32));

        LastNameInput.setBackground(new java.awt.Color(0, 0, 0));
        LastNameInput.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LastNameInput.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(LastNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 185, 196, -1));

        FirstNameInput.setBackground(new java.awt.Color(0, 0, 0));
        FirstNameInput.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        FirstNameInput.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(FirstNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 141, 196, -1));

        UsernameInput.setBackground(new java.awt.Color(0, 0, 0));
        UsernameInput.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        UsernameInput.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(UsernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 229, 196, -1));

        RankInput.setBackground(new java.awt.Color(0, 0, 0));
        RankInput.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        RankInput.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(RankInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 311, 196, -1));

        PasswordInput.setBackground(new java.awt.Color(0, 0, 0));
        PasswordInput.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PasswordInput.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(PasswordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 355, 196, -1));

        PasswordConfirmation.setBackground(new java.awt.Color(0, 0, 0));
        PasswordConfirmation.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PasswordConfirmation.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(PasswordConfirmation, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 399, 196, -1));

        BirthdateInput.setBackground(new java.awt.Color(0, 0, 0));
        BirthdateInput.setForeground(new java.awt.Color(255, 255, 255));
        try {
            BirthdateInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        BirthdateInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthdateInputActionPerformed(evt);
            }
        });
        jPanel1.add(BirthdateInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 273, 196, 32));

        confirmRegistration.setBackground(new java.awt.Color(0, 0, 255));
        confirmRegistration.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        confirmRegistration.setForeground(new java.awt.Color(255, 255, 255));
        confirmRegistration.setText("Registrate");
        confirmRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmRegistrationMouseClicked(evt);
            }
        });
        confirmRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmRegistrationActionPerformed(evt);
            }
        });
        jPanel1.add(confirmRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 488, -1, 50));

        clearRegistration.setBackground(new java.awt.Color(255, 0, 0));
        clearRegistration.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        clearRegistration.setForeground(new java.awt.Color(255, 255, 255));
        clearRegistration.setText("Clear");
        clearRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearRegistrationActionPerformed(evt);
            }
        });
        jPanel1.add(clearRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 488, 200, 50));

        backToLogin.setBackground(new java.awt.Color(0, 0, 0));
        backToLogin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        backToLogin.setForeground(new java.awt.Color(51, 255, 51));
        backToLogin.setText("Click Here To Go Back To Login!");
        backToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToLoginMouseClicked(evt);
            }
        });
        jPanel1.add(backToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, 409, 29));

        jLabel8.setIcon(new javax.swing.ImageIcon("P:\\Coding Files\\ExternalFiles\\TrueBackGround#2.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void closingSequence(){
        int choice = JOptionPane.showConfirmDialog(rootPane, "Do You Wish To Close This Window?", "SELECT AN OPTION:",JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }
    
    private void confirmRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmRegistrationActionPerformed
        if(FirstNameInput.getText().trim().isEmpty() || LastNameInput.getText().trim().isEmpty() 
             || UsernameInput.getText().trim().isEmpty() || BirthdateInput.getText().trim().isEmpty()
             || RankInput.getText().trim().isEmpty() || PasswordInput.getPassword() == null || PasswordConfirmation.getPassword() == null){
             JOptionPane.showMessageDialog(rootPane, "Unfufilled Necessary Input(s)!", "Incomplete Registration!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_confirmRegistrationActionPerformed

    private void backToLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToLoginMouseClicked
        Login lgf = new Login();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_backToLoginMouseClicked

    private void clearRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearRegistrationActionPerformed
        clearEverything();
    }//GEN-LAST:event_clearRegistrationActionPerformed

    private void BirthdateInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthdateInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthdateInputActionPerformed

    private void confirmRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmRegistrationMouseClicked
        if(FirstNameInput.getText().trim().isEmpty() || LastNameInput.getText().trim().isEmpty() 
           || UsernameInput.getText().trim().isEmpty() || BirthdateInput.getText().trim().isEmpty()
           || RankInput.getText().trim().isEmpty() || PasswordInput.getPassword() == null || PasswordConfirmation.getPassword() == null){
                JOptionPane.showMessageDialog(rootPane, "Unfufilled Necessary Input(s)", "Incomplete Registration!", JOptionPane.ERROR_MESSAGE);
        }
        
        if(!String.valueOf(PasswordInput.getPassword()).equals(String.valueOf(PasswordConfirmation.getPassword()))) {
            JOptionPane.showMessageDialog(rootPane, "Incorrect Password Entered During Confirmation", "Password Confirmation Failure!", JOptionPane.ERROR_MESSAGE);
        }
        
        String query = "INSERT INTO registeredusers VALUES (?, ?, ?, ?, ?, ?)";
        try {
            PreparedStatement ps = DataLink.getConnection().prepareStatement(query);
            ps.setString(1, FirstNameInput.getText().trim());
            ps.setString(2, LastNameInput.getText().trim());
            ps.setString(3, UsernameInput.getText().trim());
            ps.setString(4, BirthdateInput.getText().trim());
            ps.setString(5, RankInput.getText().trim());
            ps.setString(6, String.valueOf(PasswordConfirmation.getPassword()));
            int result = ps.executeUpdate();
            if (result != 0){
                clearEverything();
                JOptionPane.showMessageDialog(rootPane, "Registration Success!", "Registration Result", JOptionPane.PLAIN_MESSAGE, icon);
            }
            
        } catch (SQLException ex) {
            System.out.println("Database Insertion Failure!");
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_confirmRegistrationMouseClicked
    
    private void clearEverything(){
        FirstNameInput.setText(null);
        LastNameInput.setText(null);
        UsernameInput.setText(null);
        BirthdateInput.setText(null);
        RankInput.setText(null);
        PasswordInput.setText(null);
        PasswordConfirmation.setText(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new Registration().setVisible(true);
            }
            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField BirthdateInput;
    private javax.swing.JTextField FirstNameInput;
    private javax.swing.JTextField LastNameInput;
    private javax.swing.JPasswordField PasswordConfirmation;
    private javax.swing.JPasswordField PasswordInput;
    private javax.swing.JTextField RankInput;
    private javax.swing.JLabel RegisTitle;
    private javax.swing.JTextField UsernameInput;
    private javax.swing.JLabel backToLogin;
    private javax.swing.JButton clearRegistration;
    private javax.swing.JButton confirmRegistration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}